# Generated by Django 3.2.9 on 2022-11-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
